INSERT INTO perguntas (
  titulo,
  enunciado,
  alternativaA,
  alternativaB,
  alternativaC,
  alternativaD,
  respostaCorreta,
  materia,
  dificuldade,
  pontuacao,
  tempoLimite
) VALUES
  ('Soma simples', 'Quanto e 5 + 3?', '8', '7', '9', '6', 'A', 'Matematica', '1', 100, 20),
  ('Capital do Brasil', 'Qual e a capital do Brasil?', 'Brasilia', 'Rio de Janeiro', 'Salvador', 'Curitiba', 'A', 'Geografia', '1', 120, 20),
  ('Planeta Terra', 'Qual planeta habitamos?', 'Terra', 'Marte', 'Venus', 'Jupiter', 'A', 'Ciencias', '1', 130, 25),
  ('Alfabeto', 'Qual e a primeira letra do alfabeto?', 'A', 'B', 'C', 'D', 'A', 'Portugues', '1', 90, 15),
  ('Subtracao simples', 'Quanto e 10 - 4?', '6', '5', '7', '8', 'A', 'Matematica', '1', 110, 20),
  ('Animais', 'Qual animal mia?', 'Gato', 'Cachorro', 'Cavalo', 'Vaca', 'A', 'Ciencias', '2', 180, 25),
  ('Cores da natureza', 'Qual cor aparece no ceu em um dia limpo?', 'Azul', 'Verde', 'Vermelho', 'Roxo', 'A', 'Ciencias', '2', 170, 25),
  ('Oceano', 'Qual e o maior oceano do mundo?', 'Pacifico', 'Atlantico', 'Indico', 'Artico', 'A', 'Geografia', '2', 220, 30),
  ('Multiplicacao', 'Qual e o resultado de 6 x 7?', '42', '36', '48', '40', 'A', 'Matematica', '2', 210, 30),
  ('Literatura', 'Quem escreveu Dom Casmurro?', 'Machado de Assis', 'Carlos Drummond', 'Cecilia Meireles', 'Monteiro Lobato', 'A', 'Portugues', '2', 230, 30),
  ('Plantas', 'Qual gas as plantas absorvem na fotossintese?', 'Dioxido de carbono', 'Oxigenio', 'Nitrogenio', 'Helio', 'A', 'Ciencias', '2', 200, 30),
  ('Continentes', 'Em que continente fica o Egito?', 'Africa', 'Europa', 'Asia', 'Oceania', 'A', 'Geografia', '2', 190, 25),
  ('Divisao', 'Qual e o resultado de 15 / 3?', '5', '4', '6', '3', 'A', 'Matematica', '3', 260, 35),
  ('Vocabulario', 'Qual e o sinonimo de rapido?', 'Veloz', 'Lento', 'Pesado', 'Parado', 'A', 'Portugues', '3', 250, 35),
  ('Corpo humano', 'Qual orgao bombeia sangue pelo corpo?', 'Coracao', 'Pulmao', 'Figado', 'Rim', 'A', 'Ciencias', '3', 280, 35),
  ('Linhas imaginarias', 'Qual linha imaginaria divide a Terra em hemisferios norte e sul?', 'Equador', 'Greenwich', 'Capricornio', 'Artico', 'A', 'Geografia', '3', 270, 35),
  ('Constante pi', 'Qual e o valor de pi aproximado com duas casas decimais?', '3,14', '2,71', '1,62', '4,20', 'A', 'Matematica', '3', 290, 40),
  ('Figura de linguagem', 'Qual figura de linguagem compara usando como ou tal qual?', 'Comparacao', 'Metafora', 'Hiperbole', 'Ironia', 'A', 'Portugues', '3', 300, 40),
  ('Atomo', 'Qual particula possui carga negativa?', 'Eletron', 'Proton', 'Neutron', 'Foton', 'A', 'Ciencias', '3', 310, 40),
  ('Paises', 'Qual pais tem formato aproximado de bota?', 'Italia', 'Espanha', 'Portugal', 'Grecia', 'A', 'Geografia', '3', 320, 40),
  ('Derivada basica', 'Qual e a derivada de x^2?', '2x', 'x', 'x^3', '1', 'A', 'Matematica', '4', 380, 45),
  ('Periodos historicos', 'Qual periodo historico veio apos a Idade Media?', 'Idade Moderna', 'Idade Antiga', 'Pre Historia', 'Idade do Bronze', 'A', 'Historia', '4', 360, 45),
  ('Mitocondria', 'Qual e a funcao da mitocondria?', 'Produzir energia', 'Fazer digestao', 'Controlar audicao', 'Colorir a celula', 'A', 'Ciencias', '4', 390, 45),
  ('Populacao', 'Qual e o pais mais populoso da America do Sul?', 'Brasil', 'Argentina', 'Colombia', 'Chile', 'A', 'Geografia', '4', 370, 45),
  ('Voz verbal', 'Qual oracao esta na voz ativa?', 'O aluno resolveu o problema.', 'O problema foi resolvido pelo aluno.', 'O problema estava resolvido.', 'Havia sido resolvido o problema.', 'A', 'Portugues', '4', 400, 50);
